language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
    fast_finish: true

before_script:
  - composer install --prefer-source

script: vendor/bin/phpunit --debug
